---
title: "Reanalysing Besson et al. (2016)"
author: ""
format: pdf
editor: visual
root.dir: ""
---

```{r}
#| echo: false
library(knitr)
opts_chunk$set(fig.path='figure/', fig.align='center', fig.width=8, fig.height=8, fig.show='hold', cache=TRUE, tidy=F, tidy.opts=list(width.cutoff=60), size="small")
```

# 1. Data preparation

```{r}
#| label: besson_data_prep
library(metadat)
library(dplyr)
library(officer)
library(stringr)
library(psychometric)
X <- dat.besson2016
besson2016_ref <- docx_summary(read_docx("../Supplementary Data SD/SD 3.1 besson2016_full.docx"))$text
besson2016_ref <- strsplit(besson2016_ref, " \\(")
besson2016_ref <- data.frame("aut" = sapply(besson2016_ref, "[[", 1),
                             "year" = substr(sapply(besson2016_ref,
                                                    "[[", 2), start = 1, stop = 4))
besson2016_ref$aut <- gsub(" &", ",", besson2016_ref$aut)
besson2016_ref$aut <- gsub(" ", "", besson2016_ref$aut)
besson2016_authors_pre <- strsplit(besson2016_ref$aut, ",")

X_authors <- list()
for(i in 1:53){
X_authors[i] <- paste(paste(besson2016_authors_pre[[i]][1],
                            besson2016_authors_pre[[i]][2], collapse = ""),
      paste(besson2016_authors_pre[[i]][3], besson2016_authors_pre[[i]][4], collapse = ""),
      paste(besson2016_authors_pre[[i]][5], besson2016_authors_pre[[i]][6], collapse = ""),
      paste(besson2016_authors_pre[[i]][7], besson2016_authors_pre[[i]][8], collapse = ""),
      paste(besson2016_authors_pre[[i]][9], besson2016_authors_pre[[i]][10], collapse = ""),
      paste(besson2016_authors_pre[[i]][11], besson2016_authors_pre[[i]][12], collapse = ""),
      paste(besson2016_authors_pre[[i]][13], besson2016_authors_pre[[i]][14], collapse = ""),
      paste(besson2016_authors_pre[[i]][15], besson2016_authors_pre[[i]][16], collapse = ""),
      paste(besson2016_authors_pre[[i]][17], besson2016_authors_pre[[i]][18], collapse = ""),
      paste(besson2016_authors_pre[[i]][19], besson2016_authors_pre[[i]][20], collapse = ""), sep = ",")
}
X_authors <- gsub(" NA", "", X_authors)
X_authors <- gsub("NA", "", X_authors)
X_authors <- gsub(",,", "", X_authors)

X_authors <- gsub("Almeida S.D.S.", "Almeida S.", X_authors)
X_authors <- gsub("Almeida S.S.", "Almeida S.", X_authors)
X_authors <- gsub("De-Oliveira L.M.", "DeOliveira L.", X_authors)
X_authors <- gsub("Galler J.R.", "Galler J.", X_authors)
X_authors <- gsub("Jansen E.H.J.M.", "Jansen E.", X_authors)
X_authors <- gsub("Samuelsson A.-M.", "Samuelsson A.", X_authors)
X_authors <- gsub("Samuelsson A.M.", "Samuelsson A.", X_authors)
X_authors <- gsub("Taylor P.D.", "Taylor P.", X_authors)
  
X_author_list <- unique(unlist((strsplit(X_authors, "\\,"))))
#sort(X_author_list)

X$study_id <- X$study_ID

X$authors <- NA
for(i in 1:nrow(X)){
  X$authors[i] <- ifelse(length(which(besson2016_ref$year == str_extract(X$Reference[i], "\\d+") &
        grepl(word(X$Reference[i], 1), besson2016_ref$aut))) == 1,
        X_authors[which(besson2016_ref$year == str_extract(X$Reference[i], "\\d+") &
        grepl(word(X$Reference[i], 1), besson2016_ref$aut))], 
        NA)
}

#missing_aut <- subset(X, is.na(authors))
#unique(missing_aut$study_id)
X$authors[X$study_id == "s_01"] <- X_authors[33]
X$authors[X$study_id == "s_12"] <- X_authors[23]
X$authors[X$study_id == "s_13"] <- X_authors[35]
X$authors[X$study_id == "s_15"] <- X_authors[30]
X$authors[X$study_id == "s_17"] <- X_authors[48]
X$authors[X$study_id == "s_18"] <- X_authors[49]
X$authors[X$study_id == "s_43"] <- X_authors[9]
X$authors[X$study_id == "s_56"] <- X_authors[3]
X$authors[X$study_id == "s_57"] <- X_authors[34]
X$authors[X$study_id == "s_58"] <- X_authors[46]
X$authors[X$study_id == "s_64"] <- X_authors[8]
X$authors[X$study_id == "s_65"] <- X_authors[13]
X$authors[X$study_id == "s_79"] <- X_authors[39]

X$authors <- strsplit(X$authors, "\\,")

X <- X %>% mutate(study_id = as.integer(factor(study_id)))
```

# 2. Networks

## 2.1. Bipartite edges

```{r}
#| label: besson_bipartite_edges
X_studies <- X[!duplicated(X$study_id), ]
X_bipartite_edges <- lapply(X_studies$authors, function(x){X_author_list %in% x})
X_bipartite_edges <- do.call("cbind", X_bipartite_edges)
rownames(X_bipartite_edges) <- X_author_list
```

## 2.2. Co-author overlap network

```{r}
#| label: besson_coauthor_overlap_network
#| warning: false
par(mar = c(0,0,0,0))
library(statnet)
X_shared_authors <- t(X_bipartite_edges) %*% X_bipartite_edges
X_network <- as.network(X_shared_authors, directed = F)
plot.network(X_network, edge.col = "black",
             edge.lwd = X_shared_authors)
X_geo.dist <- geodist(X_network)
```

# 3. Analysis

## 3.1. Effect sizes

```{r}
#| label: besson_effect_sizes
library(metafor)
X$sd_c <- with(X, con_se * sqrt(con_n))
X$sd_e <- with(X, exp_se * sqrt(exp_n))
X_effect <- escalc(measure="SMD", m1i=exp_mean, m2i=con_mean, sd1i=sd_e, sd2i=sd_c,
              n1i=exp_n, n2i=con_n, data=X, add.measure=TRUE)
X_effect <- X_effect[-which(X_effect$study_id %in% unique(X_effect$study_id[is.na(X_effect$yi)])[-9]), ]
X_effect <- X_effect[-which(is.na(X_effect$yi)), ]
```

## 3.2. Correlogram

```{r}
#| label: besson_correlogram
X_effect_dist_mat <- as.matrix(stats::dist(X_effect$yi))
X_effect_sim_mat <- 1 - (X_effect_dist_mat/(max(na.omit(as.numeric(X_effect_dist_mat)))))
X_geo_dist_mat <- X_geo.dist$gdist[which(unique(X$study_id) %in% X_effect$study_id), which(unique(X$study_id) %in% X_effect$study_id)]
colnames(X_geo_dist_mat) <- 1:ncol(X_geo_dist_mat)
effects_per_study <- X_effect %>% group_by(study_id) %>% count()

geo_dist_vec <- vector()
for(i in 1:length(unique(X_effect$study_id))){
  geo_dist_vec <- c(geo_dist_vec, rep(rep(X_geo_dist_mat[i, ],
                                          times = effects_per_study$n),
                                      times = effects_per_study$n[i]))
}
X_geo_dist_mat_full <- matrix(data = geo_dist_vec, ncol = nrow(X_effect),
                              nrow = nrow(X_effect))
colnames(X_geo_dist_mat_full) <- 1:ncol(X_geo_dist_mat_full)

X_mantel_corlog <- ncf::mantel.correlog(X_geo_dist_mat_full, X_effect_sim_mat,
                                      increment = 1, resamp = 1)
plot(X_mantel_corlog)
tail(X_mantel_corlog$correlation, n = 1)
```

## 3.3. Similarity matrices

### 3.3.1. Inv.geo

```{r}
#| label: besson_similarity_matrix_invgeo
X_inv.geo <- 1 - tail(X_mantel_corlog$correlation, n = 1) *
  X_geo_dist_mat / max(X_geo_dist_mat[which(is.finite(X_geo_dist_mat))])
X_inv.geo[X_inv.geo == -Inf] <- 0
hist(X_inv.geo[X_inv.geo > 0], main = "inv.geo values > 0")
```

### 3.3.2. Jaccard

```{r}
#| label: besson_similarity_matrix_jaccard
jaccard <- function(a, b){
    intersection = length(intersect(a, b))
    union = length(a) + length(b) - intersection
    return(intersection/union)
}

X_jaccard_matrix <- matrix(data = NA, ncol = length(unique(X_effect$study_id)),
                           nrow = length(unique(X_effect$study_id)))
for(i in 1:length(unique(X_effect$study_id))){
  for(j in 1:length(unique(X_effect$study_id))){
    X_jaccard_matrix[i, j] <- jaccard(X_studies$authors[[i]], X_studies$authors[[j]])
  }
}
colnames(X_jaccard_matrix) <- unique(X_effect$study_id)[which(unique(X_effect$study_id) %in% X$study_id)]
hist(X_jaccard_matrix[X_jaccard_matrix > 0], main = "Jaccard values > 0")
```

```{r}
#| label: besson_similarity_matrix_jaccard_correlogram
jaccard_vec <- vector()
for(i in 1:length(unique(X_effect$study_id))){
  jaccard_vec <- c(jaccard_vec, rep(rep(X_jaccard_matrix[i, ],
                                          times = effects_per_study$n),
                                      times = effects_per_study$n[i]))
}
X_jaccard_mat_full <- matrix(data = jaccard_vec, ncol = nrow(X_effect),
                             nrow = nrow(X_effect))
colnames(X_jaccard_mat_full) <- 1:ncol(X_jaccard_mat_full)

X_mantel_corlog_jaccard <- ncf::mantel.correlog(X_jaccard_mat_full, X_effect_sim_mat,
                                      increment = .1, resamp = 1)
plot(X_mantel_corlog_jaccard)
head(X_mantel_corlog_jaccard$correlation, n = 1)
```

### 3.3.3. Inv.geo + Jaccard

```{r}
#| label: besson_similarity_matrix_invgeo_jaccard
X_invgeo_jaccard <- X_inv.geo + X_jaccard_matrix
colnames(X_invgeo_jaccard) <- unique(X_effect$study_id)[which(unique(X_effect$study_id) %in% X$study_id)]
hist(X_invgeo_jaccard[X_invgeo_jaccard > 0],
     main = "Combination of inv.geo and jaccard > 0")
```

## 3.4. RMA

### 3.4.1. Preparation

```{r}
#| label: besson_rma_prep
#| warning: false
library(dplyr)
colnames(X_inv.geo) <- unique(X_effect$study_id)[which(unique(X_effect$study_id) %in% X$study_id)]
X_effect$study_id.phyl <- X_effect$study_id
X_effect <- X_effect[order(X_effect$study_id), ]
X_effect <- X_effect %>%
  group_by(study_id) %>%
  mutate(obs = row_number())
X_effect$obs <- as.factor(X_effect$obs)

library(igraph)
X_effect$membership <- NA
walktrap <- graph_from_adjacency_matrix(X_shared_authors) |> cluster_walktrap()
counts <- table(X_effect$study_id)
X_effect$membership <- as.factor(rep(walktrap$membership[unique(X_effect$study_id)[which(unique(X_effect$study_id) %in% X$study_id)]], times = counts))
```

### 3.4.2. Null model

```{r}
#| label: besson_null_model
#| eval: false
X.rma.null <- rma.mv(yi ~ 1, V = vi, random = list(~ 1 | study_id, ~ 1 | comp_ID),
                     data = X_effect)
save(X.rma.null, file = "besson.rma.null.Rdata")
```

### 3.4.3. Inv.geo model

```{r}
#| label: besson_invgeo_model
#| eval: false
X.rma.full.invgeo <- rma.mv(yi ~ 1, V = vi, random = list(~ 1 | study_id,
                                                          ~ 1 | comp_ID,
                                                          ~ 1 | study_id.phyl),
                            R = list(study_id.phyl = X_inv.geo),
                     data = X_effect)
save(X.rma.full.invgeo, file = "besson.rma.full.invgeo.Rdata")
```

### 3.4.4. Jaccard model

```{r}
#| label: besson_jaccard_model
#| eval: false
X.rma.full.jaccard <- rma.mv(yi ~ 1, V = vi, random = list(~ 1 | study_id,
                                                          ~ 1 | comp_ID,
                                                          ~ 1 | study_id.phyl),
                            R = list(study_id.phyl = X_jaccard_matrix),
                     data = X_effect)
save(X.rma.full.jaccard, file = "besson.rma.full.jaccard.Rdata")
```

### 3.4.5. Inv.geo + Jaccard model

```{r}
#| label: besson_invgeo_jaccard_model
#| eval: false
X.rma.full.invgeo_jaccard <- rma.mv(yi ~ 1, V = vi, random = list(~ 1 | study_id,
                                                          ~ 1 | comp_ID,
                                                          ~ 1 | study_id.phyl),
                            R = list(study_id.phyl = X_invgeo_jaccard),
                     data = X_effect)
save(X.rma.full.invgeo_jaccard, file = "besson.rma.full.invgeo_jaccard.Rdata")
```

### 3.4.6. Summary

```{r}
#| label: bakdash_rma_all
load("besson.rma.null.Rdata")
load("besson.rma.full.invgeo.Rdata")
load("besson.rma.full.jaccard.Rdata")
load("besson.rma.full.invgeo_jaccard.Rdata")
summary(X.rma.null)
summary(X.rma.full.invgeo)
summary(X.rma.full.jaccard)
summary(X.rma.full.invgeo_jaccard)
```

## 3.5. Plots

### 3.5.1. Model comparison

```{r}
#| label: besson_model_comparison_plot
mod_comp <- data.frame("model" = c("Null model", "Invgeo model",
                                       "Jaccard model", "Invgeo jaccard model"),
                       "beta" = c(X.rma.null$beta, X.rma.full.invgeo$beta,
                                  X.rma.full.jaccard$beta,
                                  X.rma.full.invgeo_jaccard$beta),
                       "se" = c(X.rma.null$se, X.rma.full.invgeo$se,
                                X.rma.full.jaccard$se,
                                X.rma.full.invgeo_jaccard$se))

forest(mod_comp$beta, vi = mod_comp$se^2, slab = mod_comp$model,
       header = "Effect size and CI of the different models")
```

### 3.5.2. Adjusted effect sizes

#### 3.5.2.1. Calculation

```{r}
#| label: besson_adjusted_effects
#| warning: false
############################ invgeo ##############################
X_ranef_invgeo <- ranef(X.rma.full.invgeo)
rep_vec <- X_effect %>% group_by(study_id) %>% filter(!is.na(yi)) %>% count()

adjusted_effects_invgeo <- X.rma.full.invgeo$beta + rep(X_ranef_invgeo$study_id$intrcpt, rep_vec$n) +
  X_ranef_invgeo$comp_ID$intrcpt

adjusted_effects_invgeo_se <- X.rma.full.invgeo$se + rep(X_ranef_invgeo$study_id$se, rep_vec$n) +
  X_ranef_invgeo$comp_ID$se

ad_effect_dist_mat_invgeo <- as.matrix(dist(adjusted_effects_invgeo))
ad_effect_sim_mat_invgeo <- 1 - (ad_effect_dist_mat_invgeo/max(ad_effect_dist_mat_invgeo))

ad_mantel_corlog_geodist <- ncf::mantel.correlog(X_geo_dist_mat_full, ad_effect_sim_mat_invgeo, increment = 1, resamp = 0)
############################ jaccard ##############################
X_ranef_jaccard <- ranef(X.rma.full.jaccard)

adjusted_effects_jaccard <- X.rma.full.jaccard$beta + rep(X_ranef_jaccard$study_id$intrcpt, rep_vec$n) +
  X_ranef_jaccard$comp_ID$intrcpt

adjusted_effects_jaccard_se <- X.rma.full.jaccard$se + rep(X_ranef_jaccard$study_id$se, rep_vec$n) +
  X_ranef_jaccard$comp_ID$se

ad_effect_dist_mat_jaccard <- as.matrix(dist(adjusted_effects_jaccard))
ad_effect_sim_mat_jaccard <- 1 - (ad_effect_dist_mat_jaccard/max(ad_effect_dist_mat_jaccard))

ad_mantel_corlog_jaccard <- ncf::mantel.correlog(X_jaccard_mat_full, ad_effect_sim_mat_jaccard, increment = .1, resamp = 0)
```

#### 3.5.2.2. Correlogram

```{r}
#| label: besson_correlogram_adjusted
#| fig.width: 12
#| fig.height: 12
#################### CIs for invgeo ###########################
######## raw ##########
corlog_CI_invgeo <- data.frame("low" = NA, "high" = NA)
for(i in 1:length(X_mantel_corlog$correlation)){
  corlog_CI_invgeo[i, 1] <- CIr(X_mantel_corlog$correlation[i], X_mantel_corlog$n[i])[1]
  corlog_CI_invgeo[i, 2] <- CIr(X_mantel_corlog$correlation[i], X_mantel_corlog$n[i])[2]
}
######## adjusted #####
corlog_CI_ad_invgeo <- data.frame("low" = NA, "high" = NA)
for(i in 1:length(ad_mantel_corlog_geodist$correlation)){
  corlog_CI_ad_invgeo[i, 1] <- CIr(ad_mantel_corlog_geodist$correlation[i], ad_mantel_corlog_geodist$n[i])[1]
  corlog_CI_ad_invgeo[i, 2] <- CIr(ad_mantel_corlog_geodist$correlation[i], ad_mantel_corlog_geodist$n[i])[2]
}
#################### CIs for jaccard ###########################
######## raw ##########
corlog_CI_jaccard <- data.frame("low" = NA, "high" = NA)
for(i in 1:length(X_mantel_corlog_jaccard$correlation)){
  corlog_CI_jaccard[i, 1] <- CIr(X_mantel_corlog_jaccard$correlation[i], X_mantel_corlog_jaccard$n[i])[1]
  corlog_CI_jaccard[i, 2] <- CIr(X_mantel_corlog_jaccard$correlation[i], X_mantel_corlog_jaccard$n[i])[2]
}
######## adjusted #####
corlog_CI_ad_jaccard <- data.frame("low" = NA, "high" = NA)
for(i in 1:length(ad_mantel_corlog_jaccard$correlation)){
  corlog_CI_ad_jaccard[i, 1] <- CIr(ad_mantel_corlog_jaccard$correlation[i], ad_mantel_corlog_jaccard$n[i])[1]
  corlog_CI_ad_jaccard[i, 2] <- CIr(ad_mantel_corlog_jaccard$correlation[i], ad_mantel_corlog_jaccard$n[i])[2]
}
################## plot ##########################################
# combined plot:
windowsFonts(A = windowsFont("Times New Roman"))
par(mar = c(4,4,4,1), family = "A", cex = 2)
plot(X_mantel_corlog$correlation, ylim = c(.5, 1), ylab = "Effect size similarity",
                                     xlab = "Geodesic distance", main = "", cex = 0.5, las = 1, xaxt = "n")
# raw invgeo:
arrows(1, y0 = corlog_CI_invgeo[1, 1], y1 = corlog_CI_invgeo[1, 2], length = .05, angle = 90, code = 3)
arrows(2, y0 = corlog_CI_invgeo[2, 1], y1 = corlog_CI_invgeo[2, 2], length = .05, angle = 90, code = 3)
arrows(3, y0 = corlog_CI_invgeo[3, 1], y1 = corlog_CI_invgeo[3, 2], length = .05, angle = 90, code = 3)
arrows(4, y0 = corlog_CI_invgeo[4, 1], y1 = corlog_CI_invgeo[4, 2], length = .05, angle = 90, code = 3)
arrows(5, y0 = corlog_CI_invgeo[5, 1], y1 = corlog_CI_invgeo[5, 2], length = .05, angle = 90, code = 3)
arrows(6, y0 = corlog_CI_invgeo[6, 1], y1 = corlog_CI_invgeo[6, 2], length = .05, angle = 90, code = 3)
lines(1:5, X_mantel_corlog$correlation[1:5], lwd = 2)
# adjusted invgeo:
lines(1:5, ad_mantel_corlog_geodist$correlation[1:5], lwd = 2, lty = 2)
points(1:6, ad_mantel_corlog_geodist$correlation, lty = 2, cex = .5)
arrows(1, y0 = corlog_CI_ad_invgeo[1, 1], y1 = corlog_CI_ad_invgeo[1, 2], length = .05, angle = 90, code = 3, lty = 2)
arrows(2, y0 = corlog_CI_ad_invgeo[2, 1], y1 = corlog_CI_ad_invgeo[2, 2], length = .05, angle = 90, code = 3, lty = 2)
arrows(3, y0 = corlog_CI_ad_invgeo[3, 1], y1 = corlog_CI_ad_invgeo[3, 2], length = .05, angle = 90, code = 3, lty = 2)
arrows(4, y0 = corlog_CI_ad_invgeo[4, 1], y1 = corlog_CI_ad_invgeo[4, 2], length = .05, angle = 90, code = 3, lty = 2)
arrows(5, y0 = corlog_CI_ad_invgeo[5, 1], y1 = corlog_CI_ad_invgeo[5, 2], length = .05, angle = 90, code = 3, lty = 2)
arrows(6, y0 = corlog_CI_ad_invgeo[6, 1], y1 = corlog_CI_ad_invgeo[6, 2], length = .05, angle = 90, code = 3, lty = 2)
# raw jaccard
lines(seq(1, 5, len = 7), rev(X_mantel_corlog_jaccard$correlation)[1:7], lwd = 2, col = "blue")
points(seq(1, 5, len = 7), rev(X_mantel_corlog_jaccard$correlation)[1:7], col = "blue", cex = .5)
points(6.05, X_mantel_corlog_jaccard$correlation[1], col = "blue", cex = .5)
arrows(seq(1, 5, len = 7)[7], y0 = corlog_CI_jaccard[2, 1], y1 = corlog_CI_jaccard[2, 2], length = .05, angle = 90, code = 3, col = "blue")
arrows(seq(1, 5, len = 7)[6], y0 = corlog_CI_jaccard[3, 1], y1 = corlog_CI_jaccard[3, 2], length = .05, angle = 90, code = 3, col = "blue")
arrows(seq(1, 5, len = 7)[5], y0 = corlog_CI_jaccard[4, 1], y1 = corlog_CI_jaccard[4, 2], length = .05, angle = 90, code = 3, col = "blue")
arrows(seq(1, 5, len = 7)[4], y0 = corlog_CI_jaccard[5, 1], y1 = corlog_CI_jaccard[5, 2], length = .05, angle = 90, code = 3, col = "blue")
arrows(seq(1, 5, len = 7)[3], y0 = corlog_CI_jaccard[6, 1], y1 = corlog_CI_jaccard[6, 2], length = .05, angle = 90, code = 3, col = "blue")
arrows(seq(1, 5, len = 7)[2], y0 = corlog_CI_jaccard[7, 1], y1 = corlog_CI_jaccard[7, 2], length = .05, angle = 90, code = 3, col = "blue")
arrows(seq(1, 5, len = 7)[1], y0 = corlog_CI_jaccard[8, 1], y1 = corlog_CI_jaccard[8, 2], length = .05, angle = 90, code = 3, col = "blue")
arrows(6.05, y0 = corlog_CI_jaccard[1, 1], y1 = corlog_CI_jaccard[1, 2], length = .05, angle = 90, code = 3, col = "blue")
# adjusted jaccard
lines(seq(1, 5, len = 7), rev(ad_mantel_corlog_jaccard$correlation)[1:7], lty = 2, lwd = 2, col = "blue")
points(seq(1, 5, len = 7), rev(ad_mantel_corlog_jaccard$correlation)[1:7], col = "blue", cex = .5)
points(6.05, ad_mantel_corlog_jaccard$correlation[1], col = "blue", cex = .5)
arrows(seq(1, 5, len = 7)[7], y0 = corlog_CI_ad_jaccard[2, 1], y1 = corlog_CI_ad_jaccard[2, 2], length = .05, angle = 90, code = 3, col = "blue", lty = 2)
arrows(seq(1, 5, len = 7)[6], y0 = corlog_CI_ad_jaccard[3, 1], y1 = corlog_CI_ad_jaccard[3, 2], length = .05, angle = 90, code = 3, col = "blue", lty = 2)
arrows(seq(1, 5, len = 7)[5], y0 = corlog_CI_ad_jaccard[4, 1], y1 = corlog_CI_ad_jaccard[4, 2], length = .05, angle = 90, code = 3, col = "blue", lty = 2)
arrows(seq(1, 5, len = 7)[4], y0 = corlog_CI_ad_jaccard[5, 1], y1 = corlog_CI_ad_jaccard[5, 2], length = .05, angle = 90, code = 3, col = "blue", lty = 2)
arrows(seq(1, 5, len = 7)[3], y0 = corlog_CI_ad_jaccard[6, 1], y1 = corlog_CI_ad_jaccard[6, 2], length = .05, angle = 90, code = 3, col = "blue", lty = 2)
arrows(seq(1, 5, len = 7)[2], y0 = corlog_CI_ad_jaccard[7, 1], y1 = corlog_CI_ad_jaccard[7, 2], length = .05, angle = 90, code = 3, col = "blue", lty = 2)
arrows(seq(1, 5, len = 7)[1], y0 = corlog_CI_ad_jaccard[8, 1], y1 = corlog_CI_ad_jaccard[8, 2], length = .05, angle = 90, code = 3, col = "blue", lty = 2)
arrows(6.05, y0 = corlog_CI_ad_jaccard[1, 1], y1 = corlog_CI_ad_jaccard[1, 2], length = .05, angle = 90, code = 3, col = "blue", lty = 2)
# rest:
abline(v = 5.48)
abline(v = 5.52)
axis(side = 1, labels = c(0:4, Inf), at = 1:6)
text(c(1,2,3,4,5,5.9), .5,
     labels = c("n = 3639", "n = 3945", "n = 503", "n = 140", "n = 15", "n = 67,224"), cex = .5)
axis(side = 3, labels = round(rev(X_mantel_corlog_jaccard$mean.of.class),2), at = c(seq(1, 5, len = 7), 6))
text(c(seq(1, 5, len = 7), 5.9), 1,
     labels = c("n = 3703", "n = 20", "n = 397", "n = 107", "n = 206", "n = 660", "n = 42", "n = 70,331"),
     cex = .5)
mtext("Jaccard Similarity", side = 3, line = 2, cex = 2)
legend(x = 1, y = .6, legend = c("raw effects (gdist.)", "adj. effects (gdist.)", "raw effects (jaccard)", "adj. effects (jaccard)"), bty = "n", lty = c(1, 2, 1, 2), ncol = 2,
       pch = 1, col = c("black", "black", "blue", "blue"))
```

#### 3.5.2.3. Forest plot

```{r}
#| label: besson_forest_plot
#| fig.width: 12
#| fig.height: 12
set.seed(42)
studies_to_plot <- sample(1:473, 20, replace = F)
par(mar = c(4,4,1,1), family = "A")
forest(X.rma.full.invgeo$yi[studies_to_plot], vi = X.rma.full.invgeo$vi[studies_to_plot], ylim = c(-2.5, 21),
       xlim = c(-10,5), header = T, slab = X$Reference[studies_to_plot])
addpoly(adjusted_effects_invgeo[studies_to_plot], sei = adjusted_effects_invgeo_se[studies_to_plot], row = -1:18,
        col = "gray", annotate = F, border = F)
par(new = TRUE, family = "A")
forest(X.rma.full.invgeo$yi[studies_to_plot], X.rma.full.invgeo$vi[studies_to_plot], xlim = c(-10, 5), ylim = c(-2.5, 21),
       annotate = F, xlab = "", slab = NA)
addpoly(X.rma.null, row = -1, mlab = "RE Model")
addpoly(X.rma.full.invgeo, mlab = "RE Model (Adjusted Effect)")
abline(h = 0)
```
